# Generated by Django 6.0.7 on 2026-07-25 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(help_text='Common symptoms for this fault')),
                ('severity', models.CharField(choices=[('LOW', 'Low - Regular Maintenance'), ('MEDIUM', 'Medium - Plan Repair'), ('HIGH', 'High - Immediate Attention'), ('CRITICAL', 'Critical - Stop Machine')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('suggested_fault', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.fault')),
            ],
        ),
        migrations.AddField(
            model_name='fault',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='api.machinetype'),
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('steps', models.TextField(help_text='Step-by-step instructions')),
                ('tools_required', models.TextField(blank=True)),
                ('estimated_time', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXPERT', 'Expert')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='api.fault')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('weight', models.IntegerField(default=1)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='api.fault')),
            ],
        ),
    ]
